name: GCC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: list dir
        run: C:\msys64\msys2_shell.cmd -where . test.sh
      - name: print content
        run: type foobar.txt
