name: GCC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: Build gcc
        run: C:\msys64\msys2_shell.cmd -where . -no-start -defterm test.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          path: dest
          if-no-files-found: error
