name: GCC

on:
  push:

jobs:
  msys2_test:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: Test Msys2
        run: C:\msys64\msys2_shell.cmd -here -no-start -defterm test.sh
