name: GCC

on:
  push:

jobs:
  build:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: "*.tar*"
          key: ${{ runner.os }}-gcc
      - name: Build gcc
        run: C:\msys64\msys2_shell.cmd -where . -no-start -defterm test.sh
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v2.2.4
        with:
          path: dest
          if-no-files-found: error
